### ISSUE TITLE
Prometheus integration uses hard coded value for M3DB namespace

### ISSUE THREAD

**Issue by nerd0** [m3db/m3db#727]
Currently the Prometheus integration defaults to a `metrics` namespace for the coordinator to emit data to. This is not configurable thus requiring the user to strictly stick a generic namespace. To allow a bit more flexibility using configuration.  

```
coordinator:
  listenAddress: 0.0.0.0:7201

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  dbNamespace: foo
```
